services:
  app:
    # image: epicname/pen
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: /bin/bash entrypoint.sh
    ports:
      - 3000:3000
      - 5173:5173
      - 5174:5174
    working_dir: /app
    volumes:
      - ./:/app
      - exclude:/app/node_modules/
    environment:
      NODE_ENV: development
      POSTGRESQL_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kartify
      DOTENV_KEY: ${DOTENV_KEY}
  postgres:
    image: postgres:bookworm
    volumes:
      - kartifi-postgres-data:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kartify

volumes:
  kartifi-postgres-data:
  exclude: