name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the stack
      run: docker-compose up
    - name: Run tests
      run: docker-compose exec -T -w /app/packages/frontend app /bin/bash -c "yarn run test:play"
    - name: Stop containers
      if: always()
      run: docker-compose down
    # - name: Install dependencies
    #   run: yarn install --immutable --immutable-cache --check-cache
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test
    #   working-directory: packages/frontend
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
